name: Build VyOS LTS

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:sagitta
      env:
        TZ: Asia/Shanghai
      options: --privileged

    steps:
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Checkout lts branch
        uses: actions/checkout@v3
        with:
          repository: vyos/vyos-build
          ref: sagitta
          path: vyos-build

      - name: Build VyOS
        working-directory: vyos-build
        run: |
          ./configure \
            --architecture amd64 \
            --build-by ${GITHUB_ACTOR}@users.noreply.github.com \
            --build-type release \
            --version ${{ env.RELEASE_VERSION }}
          make iso
          pwd
          ls -lah
          ls -lah build

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          file: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
          asset_name: vyos-${{ env.RELEASE_VERSION }}-amd64.iso
