name: Build VyOS LTS

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:equuleus
      env:
        TZ: Asia/Shanghai
      options: --privileged

    steps:
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF_NAME}" >> $GITHUB_ENV

      - name: Checkout lts branch
        uses: actions/checkout@v3
        with:
          repository: vyos/vyos-build
          ref: equuleus
          path: vyos-build

      - name: Build VyOS
        working-directory: vyos-build
        run: |
          ./configure \
            --architecture amd64 \
            --build-by ${GITHUB_ACTOR}@users.noreply.github.com \
            --build-type release \
            --version ${{ env.RELEASE_VERSION }}
          make iso
          pwd
          ls -lah
          ls -lah build

      - name: Create release
        uses: actions/create-release@master
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            VyOS ${{ env.RELEASE_VERSION }} LTS
          draft: true
          prerelease: false

      - name: Upload release
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
          asset_name: vyos-${{ env.RELEASE_VERSION }}-amd64.iso
          asset_content_type: application/x-iso9660-image
